[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.pytest.ini_options]
minversion = "6.0"
addopts    = "--verbose --flake8 --cov tests --cov-report term-missing --cov-report xml --cov lambda_gateway"
