name: docker
on:
  push:
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 3.7
          - 3.8
    steps:
      - uses: actions/checkout@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: PYTHON_VERSION=${{ matrix.python }} docker-compose build
      - run: docker-compose push
        if: ${{ github.event_name == 'tag' }}
